apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pgsql
  name: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: pgsql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: nestjs
            - name: POSTGRES_PASSWORD
              value: pgpassword
            - name: POSTGRES_USER
              value: pguser
          image: postgres:alpine
          name: pgsql
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      restartPolicy: Always
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data
status: {}
